/**
 * Hand-curated practice order (foundational -> advanced) per category.
 * Each slug's array index becomes its `position` in Supabase.
 * DSA categories are intentionally excluded.
 */

export const ORDERINGS: Record<string, string[]> = {
  javascript: [
    // Vars, scope, hoisting
    "differences-between-var-let-and-const",
    "what-gets-hoisted-in-javascript-and-how",
    "hoisting-and-the-temporal-dead-zone-in-javascript",
    "explain-hoisting-in-javascript-with-an-example",
    // Types & equality
    "typeof-instanceof-and-reliable-type-checking-in-javascript",
    "truthy-and-falsy-values-and-equality-quirks-in-javascript",
    "double-equals-vs-triple-equals-and-coercion",
    "how-does-triple-equals-differ-from-double-equals-with-coercion",
    "implicit-vs-explicit-type-coercion-in-javascript",
    "object-reference-vs-primitive-comparison-in-javascript",
    "difference-between-nullish-coalescing-and-logical-or",
    // Functions / arrow / this / bind
    "arrow-functions-vs-regular-functions-in-javascript",
    "what-is-the-value-of-this-in-different-contexts",
    "how-does-this-behave-in-node-js-vs-the-browser",
    "can-you-bind-this-in-an-arrow-function-or-use-new-with-one",
    "explain-call-apply-and-bind-in-javascript",
    "explain-this-call-apply-and-bind",
    "how-to-preserve-object-context-with-bind-or-arrow-functions",
    "what-does-the-new-operator-do-in-javascript",
    "what-does-obj-print-log-when-print-uses-this-value",
    "when-do-function-declarations-vs-arrow-functions-impact-performance",
    // Closures / HOF / currying
    "what-is-a-closure-and-where-have-you-used-one",
    "what-are-closures-in-javascript",
    "closures-and-lexical-scoping-in-javascript",
    "what-are-higher-order-functions-in-javascript",
    "what-is-currying-in-javascript",
    "currying-and-partial-application-in-javascript",
    "common-interview-combinations-of-closures-and-currying",
    "core-javascript-concepts-closures-hoisting-event-loop-and-currying",
    // Prototypes / inheritance / OOP
    "the-prototype-chain-and-prototypal-inheritance",
    "prototypal-vs-classical-inheritance-in-javascript",
    "how-to-extend-native-objects-safely-via-the-prototype-chain",
    "how-to-use-object-oriented-programming-in-javascript",
    // Objects, destructuring, spread/rest, copies
    "how-array-and-object-destructuring-works-in-javascript",
    "spread-rest-and-destructuring-in-javascript",
    "how-to-use-the-spread-and-rest-operators-in-javascript",
    "deep-copy-vs-shallow-copy-in-javascript",
    "shallow-copy-vs-structural-sharing-in-javascript",
    // Map/WeakMap, Map vs Object
    "difference-between-map-and-object-in-javascript",
    "when-to-use-map-vs-object-in-javascript",
    "what-are-weakmap-and-weakset-and-when-to-use-them",
    "weakmap-and-weakset-use-cases",
    "when-not-to-use-map-filter-or-reduce",
    "what-algorithm-does-array-prototype-sort-use",
    // Async basics: promises, async/await
    "what-are-promises-in-javascript",
    "what-is-a-promise-and-how-do-you-resolve-one",
    "write-a-function-that-returns-a-resolved-promise",
    "write-a-program-using-a-promise-and-an-async-await-function",
    "how-does-async-await-work-in-javascript",
    "async-await-vs-promises-and-how-the-event-loop-handles-them",
    "how-async-await-differs-from-promises-internally",
    "how-does-javascript-handle-asynchronous-operations",
    "how-asynchronous-tasks-are-executed-in-javascript",
    "how-to-handle-asynchronous-code-using-async-await-and-promises",
    "error-handling-in-async-javascript",
    // Event loop, microtasks
    "what-is-node-js-and-how-does-its-event-loop-work",
    "how-the-javascript-event-loop-works",
    "javascript-event-loop-call-stack-and-task-queues",
    "javascript-execution-context-and-async-behavior",
    "difference-between-microtask-and-macrotask-queues",
    "how-the-event-loop-prioritizes-microtasks-over-macrotasks",
    "predict-execution-order-with-the-event-loop",
    "what-can-block-javascript-execution-while-running",
    "common-output-based-questions-on-promises-and-async-behavior",
    // Parallel & cancellation
    "how-to-handle-multiple-async-operations-with-promises",
    "differences-in-handling-multiple-asynchronous-operations",
    "promise-all-vs-allsettled-vs-race-vs-any",
    "how-is-promise-allsettled-different-and-when-to-use-it",
    "how-to-send-multiple-api-requests-on-a-single-button-click",
    "how-to-handle-errors-when-sending-multiple-requests-in-parallel",
    "how-to-cancel-an-in-flight-fetch-request",
    // Modules / packaging / tooling
    "esm-vs-commonjs-modules-in-javascript",
    "what-are-dynamic-imports-and-what-do-they-enable",
    "what-are-devdependencies-in-package-json",
    "difference-between-npm-and-yarn",
    // Implementations: utilities
    "implement-a-basic-debounce-function-without-a-library",
    "write-a-custom-debounce-function",
    "implement-a-debounce-function-from-scratch",
    "how-to-implement-debouncing-in-javascript",
    "how-to-implement-throttling-in-javascript",
    "implement-and-compare-debounce-and-throttle",
    "implement-debounce-and-explain-the-risks-of-wrong-timing-on-a-payment-form",
    "implement-memoization-for-an-async-function",
    // Implementations: polyfills
    "write-a-custom-implementation-of-function-prototype-bind",
    "write-a-polyfill-for-function-prototype-bind",
    "implement-a-polyfill-for-function-prototype-bind",
    "implement-a-polyfill-for-array-prototype-reduce",
    "implement-a-polyfill-for-object-assign",
    "implement-a-polyfill-for-object-create",
    "implement-a-polyfill-for-json-parse",
    "implement-a-polyfill-for-json-stringify",
    "implement-a-polyfill-for-settimeout",
    "implement-a-polyfill-for-setinterval",
    "write-a-polyfill-for-promise-all",
    "implement-a-polyfill-for-promise-allsettled",
    "implement-promise-from-scratch",
    // Implementations: data structures / patterns
    "implement-a-flatten-array-function",
    "flatten-a-deeply-nested-array-without-array-flat",
    "flatten-a-nested-array-with-custom-ordering",
    "count-the-frequency-of-elements-in-an-array",
    "find-the-sum-of-numbers-without-a-for-loop",
    "implement-a-dom-like-data-structure",
    "implement-a-chainable-driver-class",
    "implement-a-fetcher-class-with-get-and-post-methods",
    "build-react-style-class-components-from-scratch-in-es5",
    "traverse-a-deeply-nested-object-and-resolve-all-function-values",
    // Implementations: currying / event emitter / pub-sub
    "write-a-curried-mul-function-where-mul-2-3-4-equals-24",
    "implement-currying-for-an-infinite-sum-function",
    "implement-an-event-emitter-from-scratch",
    "implement-a-pubsub-or-event-emitter-from-scratch",
    "implement-a-simplified-pub-sub-or-selector-dispatch-system",
    // Concurrency / scheduling
    "execute-a-list-of-promises-in-series",
    "implement-a-task-queue-with-controlled-concurrency-and-callbacks",
    "implement-a-task-queue-with-concurrency-limit",
    "implement-an-async-scheduler-with-max-concurrency",
    "implement-limit-concurrency-using-a-worker-pool-pattern",
    // Capstone: internals interview
    "javascript-internals-closures-event-loop-and-promises",
  ],

  react: [
    // What is React: elements, JSX, fragments, portals, strict mode
    "difference-between-react-node-element-and-component",
    "how-jsx-works-and-how-react-renders-elements",
    "difference-between-createelement-and-cloneelement-in-react",
    "what-are-react-fragments-and-when-to-use-them",
    "what-are-react-portals-and-when-to-use-them",
    "what-is-react-strict-mode-and-how-does-it-affect-development",
    "why-does-react-strict-mode-behave-differently-in-development",
    "difference-between-reactdom-render-and-createroot-in-react-18",
    "differences-between-react-16-and-react-18",
    "how-react-improved-performance-compared-to-angular",
    "why-migrate-from-angular-to-react",
    "limitations-of-react-when-building-large-scale-applications",
    // Components
    "functional-vs-class-components-in-react-overview",
    "functional-vs-class-components-practical-differences",
    "difference-between-class-and-functional-components-in-react",
    "class-lifecycle-methods-vs-useeffect",
    "how-react-handles-lifecycle-in-functional-components",
    // Props vs state, immutability
    "difference-between-state-and-props-in-react",
    "props-vs-state-in-react",
    "how-state-updates-and-re-renders-work-in-react",
    "why-you-should-not-mutate-state-directly-in-react",
    "how-to-write-immutable-state-updates-in-react",
    "what-is-state-scheduling-in-react",
    "what-is-state-colocation-and-why-does-it-matter",
    "what-is-prop-drilling-in-react",
    "how-to-pass-data-from-a-parent-to-a-child-component-in-react",
    // Conditional rendering, lists, keys
    "common-conditional-rendering-patterns-in-react",
    "why-do-we-need-keys-in-react-lists",
    "why-do-react-keys-matter",
    "why-react-keys-matter-and-how-bad-keys-break-apps",
    "why-array-indices-make-bad-react-keys",
    // Event handling
    "how-event-handling-works-in-react",
    "how-does-react-handle-event-delegation",
    "how-do-react-synthetic-events-differ-from-native-dom-events",
    // Core hooks: useState, useReducer
    "what-are-react-hooks-and-how-to-create-custom-hooks",
    "explain-the-most-important-react-hooks",
    "how-to-manage-state-in-react-with-usestate-and-usereducer",
    "when-to-use-usestate-vs-usereducer",
    // useEffect deep
    "useeffect-hook-lifecycle-explained",
    "how-the-useeffect-lifecycle-works",
    "how-to-use-useeffect-for-fetching-data-from-an-api",
    "how-to-use-useeffect-to-trigger-an-api-request-with-cleanup",
    "why-do-we-need-the-dependency-array-in-useeffect",
    "how-to-debug-a-useeffect-that-is-not-working-as-expected",
    "how-does-react-handle-circular-dependencies-in-useeffect",
    "when-should-you-not-use-useeffect",
    "useeffect-vs-uselayouteffect-when-to-use-each",
    "how-react-handles-side-effects-and-how-to-manage-them",
    // Refs / forwardRef / useImperativeHandle
    "why-do-we-need-the-useref-hook-in-react",
    "when-to-use-refs-instead-of-state-in-react",
    "useref-and-forwardref-in-react",
    "what-does-forwardref-do-and-when-to-reach-for-useimperativehandle",
    "how-useimperativehandle-works-in-react",
    "how-to-expose-a-component-api-to-its-parent",
    // Memoization
    "when-to-use-usememo-vs-usecallback",
    "how-react-memo-differs-from-usememo-and-usecallback",
    "how-to-use-react-memo-usecallback-and-usememo-effectively",
    "how-react-manages-re-renders-with-memo-usememo-and-usecallback",
    "memoization-pitfalls-in-react",
    "when-memoization-helps-vs-hurts-in-react",
    "how-to-decide-which-components-need-memoization",
    "shallow-vs-deep-comparison-in-shouldcomponentupdate",
    // Stale closures
    "how-do-state-and-refs-behave-inside-a-usecallback",
    "stale-closures-in-usecallback-and-functional-updates",
    "why-setcount-count-plus-one-inside-usecallback-captures-stale-state",
    "why-functional-updates-matter-inside-usecallback-with-empty-deps",
    // Custom hooks
    "how-to-implement-custom-hooks-to-abstract-logic-in-react",
    "how-to-make-a-react-hook-reusable-across-components",
    "what-hooks-should-you-extract-for-reusability",
    "build-a-custom-fetch-hook-with-loading-and-error-states",
    "implement-a-custom-hook-that-debounces-an-input-value",
    "implement-a-custom-usedebounce-hook-from-scratch",
    "how-to-debounce-user-input-to-avoid-extra-re-renders-or-api-calls",
    "how-to-create-a-react-hook-that-syncs-state-with-localstorage",
    "build-a-custom-hook-that-syncs-state-with-localstorage-across-tabs",
    "how-to-handle-hydration-and-edge-cases-in-localstorage-hooks",
    // Forms
    "controlled-vs-uncontrolled-components-in-react",
    "controlled-vs-uncontrolled-components-with-examples",
    "how-to-handle-forms-and-validation-in-react",
    "how-to-design-good-validation-ux-in-forms",
    "how-to-manage-complex-dynamic-forms-with-conditional-fields",
    "how-to-manage-form-validation-and-state-for-dynamic-inputs",
    "how-to-structure-form-state-for-adding-and-removing-dynamic-fields",
    "how-to-store-and-access-multi-step-form-data-across-steps",
    "how-to-manage-navigation-and-validation-between-form-steps",
    // Patterns: HOC, render props
    "what-are-higher-order-components-and-how-are-they-used",
    "higher-order-components-in-react",
    "what-is-the-render-props-pattern-in-react",
    "hocs-vs-hooks-vs-render-props-in-react",
    // Context & global state foundations
    "what-is-redux-and-how-do-you-create-a-slice",
    "how-to-implement-the-react-context-api",
    "how-to-implement-context-api-for-global-state",
    "how-to-use-react-context-for-state-management",
    "how-to-pass-data-between-sibling-components-without-redux",
    "how-to-make-sibling-components-communicate-in-react",
    "when-does-react-context-cause-re-renders-and-how-to-avoid-them",
    // Redux / state libs
    "have-you-worked-with-state-management-libraries-like-zustand",
    "experience-with-redux-or-other-state-management-libraries",
    "difference-between-redux-and-redux-toolkit",
    "how-to-implement-redux-toolkit-in-a-react-app",
    "how-to-subscribe-to-a-redux-store",
    "how-thunk-based-api-calls-work-and-how-caching-behaves-in-redux",
    "compare-trade-offs-of-redux-zustand-and-context",
    "context-vs-redux-vs-zustand-when-to-use-each",
    "can-react-hooks-fully-replace-redux-for-state-management",
    "how-to-decide-between-global-and-local-state-in-react",
    "how-to-manage-global-state-efficiently-in-react",
    "best-practices-for-managing-state-in-large-react-applications",
    "strategy-for-managing-global-state-across-multiple-teams",
    "scenario-react-context-and-custom-hooks-for-a-dashboard",
    // Error boundaries
    "error-boundaries-and-crash-recovery-in-react",
    "how-to-structure-error-boundaries-per-page-and-globally",
    "how-to-show-a-per-route-fallback-ui",
    "what-fallback-ui-to-design-for-different-error-types",
    "design-a-global-error-boundary-system-for-frontend-apps",
    "how-to-prevent-errors-when-a-child-component-accesses-a-deleted-store-item",
    // Routing
    "how-to-implement-routing-in-react-with-react-router",
    "what-is-the-role-of-react-router-with-dynamic-routes",
    "implementing-protected-routes-and-auth-in-react",
    "how-to-implement-protected-routes-with-context-or-redux",
    "how-to-protect-routes-based-on-user-roles",
    "how-to-protect-routes-and-redirect-unauthenticated-users-to-login",
    "how-to-share-authentication-state-across-multiple-components-or-routes",
    "route-based-code-splitting-with-role-based-access-control",
    // Data fetching patterns
    "how-to-handle-api-calls-and-errors-in-react",
    "how-to-handle-async-code-and-state-updates-in-react",
    "ways-to-intercept-api-requests-in-a-react-project",
    "how-react-handles-parallel-api-calls-with-promise-allsettled",
    "how-to-cancel-old-api-calls-with-the-take-latest-pattern",
    "how-to-handle-loading-indicators-and-fallback-ui-during-data-fetching",
    "how-to-manage-state-for-pagination-and-loading-indicators",
    "how-to-manage-filtered-results-state-and-api-interaction",
    "how-to-separate-data-rendering-from-ui-controls",
    "optimistic-vs-pessimistic-ui-updates",
    "how-to-use-useoptimistic-for-instant-ui-updates",
    "how-does-useactionstate-manage-async-actions-and-form-state",
    "scenario-react-query-or-swr-with-optimistic-updates-for-e-commerce",
    // Real-time / dashboards
    "how-to-handle-real-time-updates-in-a-react-application",
    "scenario-real-time-chat-with-many-simultaneous-messages",
    "how-to-prevent-unnecessary-re-renders-in-a-live-dashboard",
    // Lazy / Suspense / code splitting
    "what-is-lazy-loading-in-react",
    "using-react-lazy-and-suspense-for-code-splitting",
    "how-to-use-react-lazy-and-suspense-to-load-components-on-demand",
    "lazy-load-components-with-react-lazy-and-suspense-in-protected-routes",
    // Performance & re-renders
    "why-do-react-components-re-render",
    "what-causes-unnecessary-re-renders-in-react",
    "how-unnecessary-re-renders-happen-in-react-and-how-to-avoid-them",
    "how-to-build-components-with-predictable-re-renders",
    "how-to-isolate-and-fix-unnecessary-re-renders-in-react",
    "how-to-manage-state-in-a-complex-app-to-avoid-re-renders",
    "common-performance-bottlenecks-in-react-apps",
    "how-to-distinguish-react-vs-browser-rendering-bottlenecks",
    "how-do-you-optimize-a-react-application",
    "how-to-optimize-react-applications-for-performance",
    "how-to-debug-performance-issues-in-react",
    "how-to-debug-a-react-performance-bottleneck-using-devtools",
    "how-to-reduce-initial-page-load-time-of-a-react-app-by-40-percent",
    "how-to-re-render-a-component-when-the-window-is-resized",
    // Memory leaks
    "how-to-detect-a-memory-leak-in-a-react-application",
    "how-to-handle-memory-leaks-in-react-apps",
    "how-to-debug-and-fix-a-memory-leak-in-a-react-app",
    "how-react-handles-re-renders-and-memory-management",
    // Large lists & virtualization
    "how-to-optimize-react-rendering-for-large-lists",
    "how-to-optimize-react-performance-for-large-lists-and-grids",
    "how-to-optimize-performance-in-react-with-large-component-trees",
    "how-to-optimize-rendering-of-a-react-component-with-large-datasets",
    "how-to-optimize-a-react-app-rendering-100k-items-in-a-list",
    "how-to-handle-dynamic-row-heights-in-a-virtualized-list",
    "how-to-implement-infinite-scrolling-in-react",
    "implement-an-infinite-scroll-component-with-data-fetching-and-errors",
    "implement-a-virtualized-list-for-100000-rows",
    "should-you-use-a-library-or-build-your-own-virtual-scroll",
    // SSR / hydration
    "benefits-of-server-side-rendering-in-react",
    "what-is-hydration-in-server-side-rendering",
    "how-to-handle-ssr-and-hydration-in-complex-react-apps",
    // React 18 concurrent / Fiber / RSC
    "how-reacts-rendering-process-works-under-the-hood",
    "react-reconciliation-and-the-virtual-dom",
    "how-react-reconciliation-updates-the-dom-efficiently",
    "what-is-react-fiber-and-how-it-improves-rendering",
    "explain-react-fiber-in-depth",
    "how-the-fiber-reconciliation-algorithm-works-internally",
    "what-are-the-concurrent-features-in-react-18",
    "explain-react-18-concurrent-features",
    "how-do-concurrent-rendering-and-transitions-work-in-react",
    "what-are-react-server-components",
    // Theming / dark mode
    "build-dark-mode-and-theming-in-a-react-app",
    "dynamic-theming-with-light-and-dark-mode-in-react",
    "how-to-design-and-implement-a-theme-switcher-in-react",
    "should-you-support-per-component-theming-or-global-theming",
    "how-to-persist-a-users-theme-across-sessions-and-devices",
    // Reusable building blocks
    "how-to-write-clean-component-logic-in-react",
    "how-to-build-a-reusable-ui-component-in-react",
    "how-to-extract-a-feature-into-a-reusable-component",
    "how-to-organize-components-for-maintainability",
    "different-approaches-to-styling-react-components",
    "build-a-react-list-with-collapse-and-expand",
    "implement-a-tabs-component-in-react",
    "how-to-build-a-notification-system-with-queuing-and-auto-dismiss-in-react",
    "how-to-manage-overlapping-toasts-with-priority-based-queuing",
    "how-to-queue-toasts-so-they-do-not-all-stack-at-once",
    "implement-undo-and-redo-functionality-in-a-react-app",
    "what-data-structures-to-use-for-undo-redo-history",
    "build-a-to-do-list-and-optimize-re-renders",
    // App scaffolding & architecture
    "how-to-create-a-react-app-without-create-react-app",
    "how-to-structure-code-and-state-management-in-a-frontend-app",
    "how-to-structure-a-scalable-react-application",
    "how-typescript-enhances-react-development",
    "how-to-run-a-b-tests-in-react-apps",
    // Common mistakes / production wisdom
    "common-mistakes-developers-make-in-production-react-apps",
    // Polyfills (advanced)
    "implement-a-polyfill-for-the-usestate-hook",
    "implement-a-polyfill-for-the-useeffect-hook",
    "implement-a-polyfill-for-the-useref-hook",
    "implement-a-polyfill-for-the-usememo-hook",
    "implement-a-polyfill-for-the-usecallback-hook",
    "implement-a-polyfill-for-the-usereducer-hook",
    "implement-a-polyfill-for-the-usecontext-hook",
    "implement-a-polyfill-for-the-useimperativehandle-hook",
    "implement-a-polyfill-for-the-uselayouteffect-hook",
  ],

  html: [
    "what-are-semantic-html-elements-and-why-do-they-matter",
    "how-does-srcset-work-for-responsive-images",
  ],

  typescript: [
    "when-to-use-interface-vs-type-in-typescript",
    "typescript-generics-utility-types-and-narrowing",
    "strategies-for-publishing-type-definitions-for-a-js-library",
  ],

  testing: [
    "how-to-write-unit-tests-in-react-with-jest-and-rtl",
    "how-to-test-react-components-and-api-flows-with-jest-and-rtl",
    "end-to-end-testing-with-cypress-or-playwright",
    "what-tools-would-you-use-for-frontend-testing-and-why",
    "design-a-testing-strategy-for-a-frontend-application",
  ],

  nextjs: [
    "what-is-server-side-rendering-in-next-js",
    "how-to-fetch-data-in-next-js-server-components-vs-ssg-and-ssr",
    "how-does-next-js-automatic-code-splitting-and-ssr-work",
    "what-does-the-next-js-image-component-add-over-a-plain-img",
    "how-next-js-handles-environment-variables",
    "what-is-hydration-in-next-js-and-when-it-causes-mismatches",
    "what-is-a-hydration-error-in-next-js",
    "what-causes-hydration-mismatches-in-next-js",
  ],

  accessibility: [
    "why-semantic-html-improves-accessibility",
    "what-is-the-purpose-of-the-alt-attribute-on-images",
    "key-accessibility-practices-for-frontend-engineers",
    "what-is-wcag-and-how-do-you-apply-it-in-production",
    "how-to-ensure-a-web-app-is-accessible-to-screen-reader-users",
    "how-should-screen-readers-announce-toast-notifications",
    "build-an-accessible-modal-with-focus-trap-and-aria",
    "how-to-enforce-wcag-compliance-across-teams",
    "how-to-implement-accessibility-at-scale-in-a-large-react-app",
  ],

  security: [
    // XSS fundamentals
    "safely-serialize-user-input-before-dom-insertion",
    "how-to-avoid-common-xss-pitfalls-in-frontend-frameworks",
    "how-to-prevent-xss-in-react-applications",
    "safely-render-dynamic-html-and-prevent-xss",
    // CSRF + combined
    "how-to-prevent-xss-and-csrf-attacks",
    "defend-against-csrf-and-implement-token-refresh",
    // Storage & cookies
    "risks-of-storing-auth-tokens-in-localstorage",
    "what-can-you-safely-store-in-localstorage-and-sessionstorage",
    "why-are-httponly-cookies-preferred-for-auth-tokens",
    "why-noopener-and-noreferrer-matter-on-target-blank-links",
    // CSP
    "what-breaks-when-strict-csp-blocks-inline-scripts-and-frames",
    // Auth
    "jwt-vs-session-cookies-for-authentication",
    "how-to-handle-authentication-and-authorization-in-frontend-apps",
    "how-to-implement-token-based-authentication-and-handle-token-expiry",
    "how-to-implement-role-based-access-control-on-the-frontend",
    // Holistic / advanced
    "how-to-securely-handle-sensitive-user-data-on-the-client",
    "how-to-secure-a-frontend-application-against-common-attacks",
    "how-to-prevent-a-malicious-parent-page-from-spoofing-events",
    "how-to-securely-call-and-handle-ai-api-responses",
    "how-to-handle-privacy-and-security-for-ai-features",
  ],

  networking: [
    // The lifecycle
    "how-the-web-works-from-url-to-rendered-page",
    "dns-resolution-tcp-tls-and-the-request-lifecycle",
    "what-role-do-http-headers-play-in-requests-and-responses",
    // Clients
    "key-differences-between-fetch-and-axios",
    "what-are-axios-interceptors-and-when-to-use-them",
    "what-is-rtk-query-and-how-it-differs-from-axios-or-fetch",
    // CORS
    "what-is-cors-and-how-it-works-in-the-browser",
    "how-cors-preflight-and-samesite-cookies-work-together",
    // Caching
    "how-http-caching-works-with-cache-control-and-etag",
    // REST / GraphQL
    "difference-between-rest-apis-and-graphql",
    "rest-api-design-and-conventions",
    // Cancellation & robustness
    "implement-fetch-with-timeout-and-abort",
    "how-to-cancel-api-requests-with-abortcontroller",
    "how-to-cancel-stale-api-calls-on-rapid-clicks",
    "how-to-cancel-previous-api-requests-during-rapid-updates",
    "how-to-handle-api-rate-limits-gracefully-on-the-frontend",
    "how-to-handle-rate-limits-and-errors-with-ai-apis",
    "how-to-handle-rate-limiting-and-large-payloads-with-ai-services",
    // Real time
    "why-use-websockets-instead-of-http-polling",
    "how-to-build-real-time-features-with-websockets-or-sse",
    "when-to-use-websockets-vs-sse-vs-polling",
  ],

  css: [
    // Box model & units
    "what-is-the-css-box-model-conceptually",
    "css-box-model-content-box-vs-border-box",
    "difference-between-rem-em-and-px-in-css",
    // Selectors, specificity, pseudo
    "how-does-css-specificity-and-the-cascade-work",
    "what-are-pseudo-classes-and-pseudo-elements-in-css",
    // Display / visibility
    "difference-between-display-none-and-visibility-hidden",
    "display-none-vs-visibility-hidden-vs-opacity-zero",
    // Position
    "css-position-values-and-when-to-use-each",
    "practical-uses-of-css-position-values",
    // Custom properties
    "what-are-css-custom-properties-and-how-to-use-them",
    // Flexbox basics & centering
    "how-to-center-a-div-inside-another-div",
    "how-to-center-a-div-horizontally-and-vertically",
    "how-to-assign-different-widths-to-flex-items",
    "inline-five-divs-in-a-row-without-flex-or-margin",
    // Flex vs Grid
    "when-to-use-flexbox-vs-css-grid",
    "real-world-differences-between-flexbox-and-css-grid",
    "flexbox-or-grid-for-an-e-commerce-product-layout",
    "design-a-responsive-grid-layout-with-css-grid-and-flexbox",
    // Responsive design
    "why-does-the-viewport-meta-tag-matter-for-mobile-ui",
    "how-to-make-a-web-app-responsive-with-media-queries-and-relative-units",
    "css-methodologies-bem-and-responsive-media-queries",
    "responsive-design-mobile-first-breakpoints-and-container-queries",
    "how-to-build-fully-responsive-web-applications",
    "how-to-create-a-responsive-design-from-scratch",
    // Architecture / scale
    "why-choose-tailwind-css-over-bootstrap-or-traditional-css",
    "how-to-manage-styles-in-large-scale-applications",
    // Cross-browser
    "approach-to-cross-browser-consistency-in-production",
    "how-to-ensure-consistent-rendering-across-browsers",
    "how-to-troubleshoot-intermittent-ui-glitches-across-browsers",
    "how-to-troubleshoot-intermittent-cross-browser-ui-glitches",
  ],

  behavioral: [
    // Self-intro / motivation warmups
    "where-do-you-see-yourself-growing-in-the-next-few-years",
    "why-do-you-want-to-join-this-company",
    "why-do-you-want-to-join-this-fintech-company",
    // STAR / answer framework foundations
    "how-to-prepare-star-stories-for-leadership-principles",
    "how-to-use-the-star-format-for-conflict-resolution-answers",
    "how-to-structure-answers-for-conflict-deadline-and-ownership-questions",
    "how-to-prepare-for-leadership-ownership-and-teamwork-questions",
    // Past projects
    "describe-the-most-challenging-project-in-your-experience",
    "walk-me-through-a-past-project-sdlc-debugging-and-observability",
    "walk-me-through-your-project-responsibilities-and-architecture-diagram",
    "walk-me-through-a-frontend-architecture-you-designed",
    "scenario-based-discussion-on-past-projects-and-ownership",
    "describe-a-time-you-owned-a-project-beyond-your-responsibility",
    "where-have-you-used-virtualization-in-your-projects",
    "walk-me-through-a-performance-optimization-project",
    "tell-me-about-a-react-performance-optimization-that-failed",
    // Conflict & communication
    "tell-me-about-a-time-you-had-a-conflict-with-a-teammate",
    "how-to-handle-disagreements-on-technical-approach",
    "how-do-you-handle-disagreements-with-pms-or-designers",
    "how-to-handle-conflicts-with-designers-or-backend-teams",
    "how-to-resolve-implementation-disagreements-with-designers-or-backend-engineers",
    "how-do-you-handle-communication-between-different-teams",
    "how-to-communicate-complex-technical-decisions-to-non-technical-stakeholders",
    // Deadlines / scope / requirements
    "how-do-you-handle-vague-or-incomplete-requirements",
    "how-do-you-handle-tight-deadlines-without-sacrificing-quality",
    "how-to-manage-work-under-tight-deadlines",
    "tell-me-about-a-time-you-delivered-a-feature-under-a-tight-deadline",
    // Quality, tech debt, process
    "how-to-run-code-reviews-and-maintain-quality-standards",
    "how-to-manage-technical-debt-in-a-frontend-codebase",
    "how-to-prioritize-technical-debt-vs-new-features",
    "how-to-handle-version-control-and-collaboration-with-git",
    "what-is-git-rebase-and-how-does-it-differ-from-merge",
    "what-is-a-jira-backlog-vs-a-feature-backlog",
    // Production readiness & incidents
    "how-to-decide-if-an-app-is-ready-for-production-deployment",
    "walk-through-a-bug-you-shipped-to-production",
    "describe-a-time-your-production-build-caused-a-major-ui-issue",
    "how-would-you-handle-a-critical-production-ui-bug",
    "tell-me-about-a-time-you-led-incident-response-for-a-production-bug",
    "how-to-mitigate-a-critical-ui-feature-failing-during-peak-traffic",
    "what-do-the-first-ten-minutes-look-like-when-checkout-goes-down",
    "how-does-high-transaction-volume-change-how-you-think-about-frontend-changes",
    // Design defense / interview-craft
    "how-to-defend-architectural-choices-in-an-interview",
    "how-to-explain-design-decisions-in-an-interview",
    // Leadership, mentoring, AI tooling
    "how-to-mentor-juniors-and-conduct-interviews",
    "how-do-you-use-ai-tools-in-your-development-workflow",
  ],

  "machine-coding": [
    // Primitives & inputs
    "build-a-reusable-button-with-variants-and-sizes",
    "build-a-star-rating-component",
    "build-an-otp-input-component",
    "build-a-stepper-or-progress-tracker-component",
    "build-a-stopwatch-or-timer-component",
    "build-a-stopwatch-with-pause-and-millisecond-precision",
    "build-concurrent-progress-bars-for-parallel-tasks",
    "build-a-cursor-tracker-component",
    // Dropdowns & menus
    "build-a-custom-dropdown-component",
    "create-a-reusable-dropdown-with-search-and-multi-select",
    // Tabs / accordions / disclosure
    "build-a-tabs-component-from-scratch",
    "build-an-accessible-tabs-component",
    "build-an-accordion-component",
    "build-an-accessible-accordion-component",
    // Modals / dialogs / toasts
    "build-a-modal-component-from-scratch",
    "build-a-reusable-accessible-dialog-component",
    "design-a-modal-management-system",
    "build-a-priority-based-modal-system",
    "build-a-toast-notification-system-with-queueing",
    // Forms
    "build-a-login-form-with-validation-and-state-management",
    "build-a-login-form-covering-state-validation-a11y-and-security",
    "build-a-multi-step-form-with-validation",
    "build-a-tab-based-form-with-two-sections",
    "build-a-reusable-component-with-search-functionality",
    // Search / autocomplete (debounce)
    "create-a-debounced-search-feature",
    "build-a-debounced-search-box-component",
    "build-a-debounced-search-autocomplete-component",
    "build-a-search-feature-with-debounce-and-api-calls",
    "build-an-autocomplete-or-typeahead-component",
    "how-to-architect-a-search-bar-with-debounce-and-async-suggestions",
    // To-do apps (canonical machine coding)
    "create-a-todo-list-application-with-add-and-delete",
    "build-a-to-do-app-for-a-machine-coding-round",
    "build-a-to-do-app-with-add-edit-delete-and-filters",
    "build-a-to-do-app-that-avoids-unnecessary-re-renders",
    "build-a-simple-task-management-interface",
    // Carousels / image viewers
    "build-an-image-carousel-from-scratch",
    "build-an-image-carousel-component",
    // Grids & light-box games
    "build-a-dynamic-grid-component",
    "build-a-grid-toggle-ui-with-immutable-state",
    "build-a-grid-light-box-with-reverse-deactivation",
    "build-a-capital-and-country-matching-game",
    "implement-tic-tac-toe-in-react",
    // Trees / hierarchical
    "build-a-collapsible-folder-tree-with-nested-checkboxes",
    "build-a-file-explorer-ui-component",
    "build-a-file-explorer-with-nested-folder-tree",
    // Drag & drop / interactions
    "build-a-drag-and-drop-feature",
    // Lists / virtualization / infinite
    "implement-infinite-scrolling-from-scratch",
    "build-a-virtualized-list-for-very-large-datasets",
    // Tables
    "design-a-reusable-table-with-sort-filter-and-pagination",
    // Carts & checkout
    "build-a-shopping-cart-ui",
    "implement-a-cart-system-with-real-time-price-updates",
    "persist-cart-state-across-page-refreshes-using-localstorage",
    "build-a-transaction-confirmation-flow",
    "build-a-product-listing-page-with-search-filters-and-cart",
    // Domain widgets
    "build-a-weather-widget-in-react",
    "build-a-cricket-scoreboard-ui-low-level-design",
    "build-a-google-calendar-style-week-view",
    // Full apps & architecture
    "build-a-complete-frontend-app-that-consumes-apis-and-is-responsive",
    "build-a-full-react-application-from-scratch",
    "build-a-reusable-ui-component-with-modularity-and-performance-in-mind",
    "build-a-frontend-app-with-strong-code-quality-and-scalability",
    "build-a-collaborative-text-editor-like-google-docs",
    // Meta / follow-ups
    "common-follow-up-questions-after-a-machine-coding-round",
  ],

  performance: [
    // What & why: rendering models
    "differences-between-ssr-and-csr",
    "what-is-client-side-rendering-and-when-is-it-beneficial",
    "rendering-techniques-csr-vs-ssr-vs-streaming",
    "when-to-use-ssr-vs-ssg-vs-csr",
    "ssr-vs-ssg-vs-csr-for-ai-generated-content",
    "how-performance-ssr-and-seo-interact",
    // Metrics
    "explain-the-key-web-performance-metrics",
    "what-performance-metrics-do-you-track-in-production",
    "web-vitals-lcp-inp-and-cls-explained",
    "how-to-optimize-core-web-vitals",
    "first-contentful-paint-and-what-blocks-it",
    "largest-contentful-paint-what-slows-it-down-and-how-to-fix-it",
    "what-is-cumulative-layout-shift-and-how-to-control-it",
    "how-to-improve-interaction-to-next-paint",
    "time-to-first-byte-measuring-and-improving-it",
    "total-blocking-time-and-how-to-reduce-main-thread-blocking",
    "how-to-reduce-time-to-interactive",
    "how-to-measure-and-improve-lighthouse-scores",
    "how-to-measure-performance-in-real-world-projects",
    "how-to-measure-and-quantify-the-impact-of-a-performance-fix",
    "how-to-explain-frontend-performance-metrics-to-non-technical-stakeholders",
    // Bundling, tree-shaking, code splitting
    "how-the-webpack-build-process-works",
    "how-tree-shaking-and-bundling-work",
    "how-does-tree-shaking-remove-unused-code-in-bundlers",
    "code-splitting-with-dynamic-imports",
    "difference-between-code-splitting-and-chunking",
    "why-is-code-splitting-better-than-loading-everything-at-once",
    "how-code-splitting-and-lazy-loading-improve-performance",
    "code-splitting-strategies-route-component-and-vendor",
    "how-have-you-implemented-code-splitting-in-your-project",
    "how-to-optimize-bundle-splitting",
    "how-to-analyze-and-optimize-a-frontend-bundle",
    "how-to-reduce-bundle-size-in-production",
    // Loading strategies & resource hints
    "what-are-render-blocking-resources",
    "what-is-critical-css-extraction-and-why-does-it-matter",
    "what-are-resource-hints-in-html",
    "what-are-preload-preconnect-prefetch-and-prerender",
    "preload-prefetch-and-lazy-loading-compared",
    "preload-prefetch-preconnect-and-dns-prefetch-explained",
    "lazy-loading-vs-preloading-vs-prefetching",
    "javascript-script-loading-strategies-defer-async-and-modulepreload",
    "what-is-lazy-loading-and-how-to-implement-it",
    "how-to-optimize-third-party-script-loading",
    // Caching & CDN
    "common-http-caching-strategies",
    "how-to-implement-caching-on-a-website",
    "cdn-and-asset-optimization-for-performance",
    // Images & assets
    "how-to-optimize-assets-and-choose-between-webp-png-and-jpg",
    "frontend-image-optimization-techniques",
    "how-to-optimize-images-in-a-large-web-app",
    "lazy-loading-combined-with-image-optimization",
    // CSS / rendering perf
    "how-to-optimize-css-for-performance",
    "repaint-vs-reflow-and-avoiding-layout-thrashing",
    "repaint-vs-reflow-vs-composite-what-triggers-each",
    "how-to-reduce-reflows-and-repaints-in-the-browser",
    "which-css-properties-should-you-avoid-animating",
    "why-transform-is-preferred-over-animating-layout-properties",
    "how-to-identify-and-fix-janky-css-animations-on-mobile",
    // Debouncing / throttling / events
    "when-to-use-debouncing-vs-throttling",
    "how-to-implement-debounced-inputs-for-better-performance",
    "how-to-use-throttling-and-debouncing-to-prevent-excessive-requests",
    "how-to-handle-and-optimize-performance-of-drag-events",
    // Memoization & re-renders
    "using-memoization-to-reduce-re-renders",
    // Large lists & virtualization
    "what-is-virtualization-and-when-to-use-it",
    "when-should-you-reach-for-virtualization",
    "rendering-big-lists-with-windowing-and-virtualization",
    "performance-model-of-infinite-scroll-and-virtual-lists",
    "how-to-optimize-rendering-of-a-list-with-ten-thousand-items",
    "how-to-render-5000-records-in-a-dropdown-efficiently",
    "how-to-avoid-rendering-offscreen-dom-nodes",
    "how-to-optimize-the-filtering-process-for-large-datasets",
    "how-to-render-a-large-dataset-without-blocking-the-main-thread",
    "how-to-handle-large-data-from-api-efficiently",
    "how-to-manage-performance-of-a-large-undo-stack",
    // Data fetching
    "what-is-your-approach-to-efficient-data-fetching",
    // Holistic / scale
    "how-to-optimize-web-performance-and-reduce-load-times",
    "techniques-to-ensure-performance-and-responsiveness",
    "strategies-to-improve-page-load-time-for-a-global-audience",
    "how-to-optimize-frontend-performance-at-scale",
    "what-challenges-have-you-faced-when-building-for-large-user-traffic",
    // Debug & triage
    "how-to-profile-and-optimize-a-laggy-dashboard-on-filter-changes",
    "your-app-feels-slow-but-lighthouse-score-is-good-why",
  ],

  "system-design": [
    // Fundamentals & interview approach
    "what-does-scalable-web-applications-mean-to-you",
    "frontend-system-design-fundamentals",
    "how-to-approach-a-frontend-whiteboard-system-design-round",
    "high-level-design-walkthrough-of-a-past-frontend-system",
    "what-are-the-solid-principles-for-frontend-engineers",
    "writing-pure-functions-for-testable-frontend-code",
    // Component architecture
    "what-is-component-driven-architecture",
    "how-to-build-components-for-scalability-and-reuse",
    "what-reusable-components-or-patterns-would-you-build",
    "design-a-reusable-toast-notification-system-from-scratch",
    "design-a-reusable-table-component-with-sorting-filtering-pagination",
    "how-to-build-a-component-library-used-by-multiple-teams",
    "how-to-design-a-reusable-component-library-across-teams",
    "how-to-scale-a-design-system-across-multiple-teams",
    // Library / SDK / package design
    "what-to-consider-when-designing-a-library-api",
    "how-to-design-a-tree-shakable-javascript-library",
    "how-to-build-and-publish-your-own-npm-package",
    "esm-vs-cjs-output-for-a-published-library",
    "release-strategy-for-a-javascript-library",
    "how-to-maintain-backward-compatibility-for-a-published-package",
    "how-to-expose-an-sdk-api-without-polluting-the-global-namespace",
    "caret-vs-tilde-in-package-json",
    "when-and-how-to-use-peer-dependencies",
    "how-to-manage-dependencies-when-a-library-upgrade-breaks-a-component",
    // App-level structure
    "how-to-structure-a-large-scale-react-application",
    "how-to-structure-and-optimize-a-large-scale-react-codebase",
    "how-to-structure-a-modular-frontend-application",
    "how-to-structure-a-scalable-frontend-app-with-many-pages",
    "how-to-design-a-scalable-react-dashboard-with-many-pages",
    "how-to-choose-a-routing-strategy-for-a-large-frontend-app",
    "how-to-architect-an-application-to-support-multiple-devices",
    // Code splitting & perf at scale
    "how-to-approach-code-splitting-in-frontend-architecture",
    "frontend-system-design-for-performance-ssr-and-seo",
    "how-to-design-an-offline-first-frontend",
    "what-problems-do-web-workers-actually-solve",
    // State management
    "how-to-layer-state-management-in-a-frontend-app",
    "design-a-client-side-state-management-system-like-redux-toolkit",
    // Data fetching, caching, retries
    "build-a-priority-based-data-fetching-system",
    "how-to-design-client-side-caching-api-retries-and-error-boundaries",
    "design-a-rate-limiter-for-api-calls-in-a-spa",
    // Theming
    "how-to-implement-dynamic-theming-in-a-large-web-application",
    // Feature flags & rollout
    "implement-a-reusable-feature-toggle-system",
    "how-to-manage-feature-flags-at-scale",
    "how-to-design-a-frontend-feature-flag-system",
    "how-to-roll-out-feature-flags-safely-in-production",
    "how-to-implement-a-b-testing-without-affecting-current-users",
    // CI/CD, monorepo, migration
    "how-to-set-up-ci-cd-for-multi-environment-apps",
    "how-to-manage-shared-dependencies-in-a-monorepo",
    "how-to-migrate-legacy-apps-to-modern-frontend-stacks",
    "how-to-plan-a-migration-of-a-legacy-frontend-to-a-modern-framework",
    // Monitoring
    "monitoring-and-error-tracking-strategy-for-frontend",
    "how-to-implement-frontend-monitoring-and-logging",
    // Auth
    "design-a-user-authentication-flow-with-oauth-and-jwt",
    // Micro-frontends
    "what-is-micro-frontend-architecture-and-when-would-you-use-it",
    "how-do-independent-deploys-work-in-a-micro-frontend-setup",
    "how-to-share-common-functions-or-libraries-in-a-micro-frontend",
    "build-an-embeddable-checkout-widget-loaded-via-a-script-tag",
    // Real-time / collaboration
    "how-to-build-a-real-time-order-tracker-with-websockets",
    "build-a-real-time-order-tracker-with-websockets",
    "how-to-handle-real-time-cursor-typing-and-presence-indicators",
    "how-to-handle-sync-conflicts-and-operational-transforms",
    "design-a-real-time-collaborative-text-editor-like-google-docs",
    "design-a-real-time-collaborative-dashboard",
    "design-a-performant-web-app-with-large-data-tables-and-real-time-updates",
    // AI features
    "what-are-llms-and-slms-from-a-frontend-perspective",
    "difference-between-ai-and-generative-ai",
    "ux-challenges-unique-to-ai-interfaces",
    "how-to-integrate-an-ai-api-like-openai-or-claude-into-a-frontend-app",
    "how-to-stream-ai-responses-to-the-ui-in-real-time",
    "how-to-build-a-scalable-chat-ui-for-an-llm-product",
    // 2D / grids / canvas-ish
    "how-to-design-2d-data-structures-for-grids-and-matrices",
    // Classic LLD / HLD products
    "design-an-autocomplete-like-flipkart-search-bar-high-level-design",
    "design-a-poll-widget",
    "design-the-frontend-for-a-product-listing-page",
    "design-an-e-commerce-frontend-with-filters-at-scale",
    "design-the-send-message-feature-like-slack",
    "how-to-design-the-data-model-for-a-chat-application-ui",
    "design-a-chat-application-like-messenger",
    "design-whatsapp-web-at-a-high-level",
    "design-a-news-feed-like-facebook",
    "design-a-facebook-style-social-media-feed",
    "design-an-instagram-style-feed-page",
    "design-a-photo-sharing-app-like-instagram",
    "design-a-product-like-pinterest",
    "design-a-jira-style-kanban-board",
    "design-a-three-column-jira-style-board",
    "design-a-calendar-application-like-google-calendar",
    "design-a-calendar-ui-like-google-calendar",
    "design-a-video-streaming-service-like-netflix",
    "design-a-payment-gateway-for-transaction-flow-and-reliability",
    "low-level-design-a-delivery-system-ui-for-drivers",
    "design-a-phone-style-web-app-low-level-design",
    "design-and-implement-an-atm-machine-low-level-design",
    "design-browser-like-features-tabs-history-and-shortcuts",
    "how-to-build-a-maps-app-with-tile-loading-and-ui-responsiveness",
    "design-a-dynamic-pagination-system-for-infinite-scrolling",
    "design-infinite-scroll-for-millions-of-items",
    "how-to-design-a-realtime-scalable-gaming-dashboard",
    // Scale capstones
    "how-to-design-a-frontend-architecture-for-one-million-daily-users",
  ],

  "browser-internals": [
    // Rendering pipeline
    "how-browsers-render-html-css-and-javascript",
    "how-does-the-browser-render-a-webpage",
    "what-happens-when-you-hit-a-url-in-the-browser",
    "what-happens-from-button-click-to-network-request-leaving-the-browser",
    "critical-rendering-path-how-browsers-render-a-page",
    "what-is-the-critical-rendering-path",
    "explain-the-critical-rendering-path-and-the-cssom",
    "what-blocks-the-critical-rendering-path",
    "what-events-fire-during-page-load-and-the-critical-rendering-path",
    // Repaint / reflow
    "the-difference-between-repaint-and-reflow",
    "reflow-vs-repaint-when-does-each-happen",
    // Events
    "event-propagation-bubbling-vs-capturing-in-the-dom",
    "event-bubbling-capturing-and-delegation",
    "event-delegation-and-bubbling-in-the-dom",
    "how-does-event-delegation-work-and-why-is-it-efficient",
    "how-to-approach-dom-manipulation-event-listeners-and-styling-in-vanilla-js",
    // Storage
    "web-storage-apis-localstorage-sessionstorage-and-cookies",
    "browser-storage-localstorage-sessionstorage-cookies-and-indexeddb",
    "when-to-use-cookies-localstorage-or-sessionstorage",
    "can-another-domain-access-localstorage-data-from-a-different-domain",
    "what-are-etag-cache-control-and-document-fragment",
    // Service workers / PWA
    "what-is-a-service-worker-in-the-browser",
    "what-service-workers-do-and-how-to-use-them",
    "what-are-service-workers-and-how-do-they-enable-pwas",
    "what-are-progressive-web-apps-and-their-benefits",
    "how-pwa-features-improve-user-experience",
    // Multi-tab sync
    "how-to-keep-multiple-browser-tabs-in-sync",
    // Memory & GC
    "what-happens-if-a-browser-tab-reaches-its-memory-limit",
    "what-triggers-garbage-collection-in-javascript",
    "common-memory-leaks-in-single-page-applications",
    "how-to-identify-and-fix-a-memory-leak-in-a-production-spa",
    "how-does-javascript-garbage-collection-work-internally",
    "why-does-deleting-object-properties-affect-v8-optimization",
    // Debugging
    "how-to-debug-javascript-and-react-applications-effectively",
  ],
};
