/**
 * Manually-extracted prompts from txt files whose formatting the regex
 * extractor can't pick up reliably (free-prose narratives, topic lists with
 * no question marks, mixed Unicode bullets that already broke once, etc.).
 *
 * Each entry below was extracted by reading the source file end-to-end and
 * turning every distinct interview-relevant topic into a single, well-formed
 * question prompt. These join the regex-extracted prompts before the dedupe
 * step, so duplicates collapse naturally.
 */
import type { ExtractedQuestion } from "./types";

interface ManualEntry {
  sourceFile: string; // e.g. "6.txt"
  prompts: string[];
}

const MANUAL: ManualEntry[] = [
  {
    sourceFile: "3.txt",
    prompts: [
      "Implement Tic Tac Toe in React",
      "Implement a reusable feature toggle system with multiple conditions",
      "Design the 3-column functionality (open / in progress / completed) of a Jira board",
      "Behavioral: how do you resolve conflict in a team using STAR?",
      "Behavioral: how do you handle tight deadlines?",
    ],
  },
  {
    sourceFile: "6.txt",
    prompts: [
      "Implement a polyfill for Function.prototype.bind",
      "Implement a polyfill for Function.prototype.call",
      "Implement a polyfill for Function.prototype.apply",
      "Implement a Promise polyfill from scratch",
      "Implement a polyfill for debounce",
      "Implement a polyfill for throttle",
      "Implement a polyfill for setTimeout",
      "Implement a polyfill for setInterval",
      "Implement a polyfill for Array.prototype.map",
      "Implement a polyfill for Array.prototype.filter",
      "Implement a polyfill for Array.prototype.reduce",
      "Implement a polyfill for Array.prototype.forEach",
      "Implement a polyfill for Array.prototype.find",
      "Implement a polyfill for Array.prototype.findIndex",
      "Implement a polyfill for Array.prototype.some",
      "Implement a polyfill for Array.prototype.every",
      "Implement a polyfill for Array.prototype.flat",
      "Implement a polyfill for Object.create",
      "Implement a polyfill for Object.assign",
      "Implement a polyfill for JSON.stringify",
      "Implement a polyfill for JSON.parse",
      "Implement a polyfill for useState",
      "Implement a polyfill for useEffect",
      "Implement a polyfill for useMemo",
      "Implement a polyfill for useCallback",
      "Implement a polyfill for useContext",
      "Implement a polyfill for useReducer",
      "Implement a polyfill for useRef",
      "Implement a polyfill for useLayoutEffect",
      "Implement a polyfill for useImperativeHandle",
    ],
  },
  {
    sourceFile: "15.txt",
    prompts: [
      "Explain the use cases of Trees and Binary Search Trees in frontend interviews",
      "Two-pointer technique — when do you reach for it?",
      "Sliding window technique — how it solves substring/subarray problems",
      "Binary search and its variants in interviews",
      "Stacks and queues — common interview applications",
      "BFS vs DFS on graphs — when to use which",
      "How to use var, let, and const correctly",
      "What is hoisting in JavaScript?",
      "How do closures work?",
      "How to implement debouncing",
      "How to implement throttling",
      "What is currying in JavaScript?",
      "Difference between == and === in JavaScript",
      "How does the `this` keyword work in JavaScript?",
      "How to use call, apply, and bind",
      "What are prototypes and prototypal inheritance?",
      "How to use the spread and rest operators",
      "How does array and object destructuring work?",
      "What are Promises in JavaScript?",
      "How async/await works in JavaScript",
      "What are higher-order functions?",
      "Explain JSX and how React renders elements",
      "Functional vs class components in React",
      "Props vs state in React",
      "Class lifecycle methods vs useEffect",
      "Event handling in React",
      "Conditional rendering patterns in React",
      "Why do React lists need keys?",
      "Higher-Order Components (HOC) in React",
      "Render props pattern in React",
      "What are React Portals and when to use them?",
      "Build a Todo App machine-coding round",
      "Build a debounced search box",
      "Build an autocomplete component",
      "Build a custom dropdown component",
      "Build a modal component (focus trap, ARIA)",
      "Build an accordion / expandable list",
      "Build an infinite scroll list",
      "Build a tabs component",
      "Build a form with validation",
      "Build a stopwatch / timer",
      "Build a star rating component",
      "Build a stepper / progress tracker",
      "Build a carousel / image slider",
      "Frontend system design: design a Poll widget",
      "Frontend system design: design a News Feed (Facebook)",
      "Frontend system design: design Photo Sharing (Instagram)",
      "Frontend system design: design an E-commerce app (Amazon)",
      "Frontend system design: design a Chat App (Messenger)",
      "Frontend system design: design Video Streaming (Netflix)",
      "Frontend system design: design Pinterest",
    ],
  },
  {
    sourceFile: "18.txt",
    prompts: [
      "Walk me through your role designing a frontend architecture",
      "Performance strategies: critical CSS extraction",
      "Performance strategies: code splitting and dynamic imports",
      "Performance strategies: lazy loading with image optimization",
      "Performance strategies: memoization to reduce re-renders",
      "Performance strategies: debounced inputs",
      "Semantic HTML and accessibility practices",
      "CSS methodologies like BEM and responsive media queries",
      "Behavioral: describe a time you owned a project beyond your responsibility",
      "DSA: return the k-th largest element in an array",
      "Given a BST, return a balanced version with the same nodes",
      "Word Break II — string segmentation using a dictionary",
      "Behavioral STAR: a time conflict between you and teammates arose",
      "For each element, count the numbers to its right that are smaller",
    ],
  },
  {
    sourceFile: "21.txt",
    prompts: [
      "Build a Grid Light Box in React (lights deactivate in reverse order of activation)",
      "Implement memoization for an async function with callbacks (cache, deep equality, parallel calls)",
      "Behavioral: how do you handle disagreements with PMs or designers?",
      "DSA: zombie spread on a grid (multi-source BFS)",
      "Frontend system design: design WhatsApp Web (HLD)",
    ],
  },
  {
    sourceFile: "22.txt",
    prompts: [
      "Output-based questions on `this`, arrow functions, and call/apply/bind",
      "Implement a currying problem in JavaScript",
      "Implement a polyfill for Array.prototype.reduce",
      "Implement fetch with a timeout/abort feature",
      "Implement prototypal inheritance from scratch",
      "Build a login form with structure, validation, and state management",
    ],
  },
  {
    sourceFile: "23.txt",
    prompts: [
      "How would you prepare DOM manipulation, event listeners, and styling with vanilla JS?",
      "Frontend system design fundamentals (component structure, state, performance)",
      "Behavioral: prepare 1–2 STAR stories per leadership principle",
    ],
  },
  {
    sourceFile: "25.txt",
    prompts: [
      "Implement a task queue with controlled concurrency (success/error callbacks, custom executors)",
      "Build a Modal Management system",
      "Frontend system design: design a Calendar application like Google Calendar",
      "Behavioral: leadership, ownership, teamwork, and past experiences",
    ],
  },
  {
    sourceFile: "29.txt",
    prompts: ["Build a reusable component with search functionality"],
  },
  {
    sourceFile: "31.txt",
    prompts: [
      "Hoisting and closures",
      "Browser storage: localStorage vs sessionStorage vs cookies vs IndexedDB",
      "WebSockets vs HTTP — and why aggressive polling is a bad idea",
      "CSS Box Model and centering techniques",
      "Output-based JS questions on Promises and async behavior",
      "Build a Grid Toggle UI component (immutable state, 2D structures, predictable re-renders)",
    ],
  },
  {
    sourceFile: "32.txt",
    prompts: [
      "`this` binding in regular vs arrow functions",
      "Closures and currying — common interview combinations",
      "Async JS: API fetch with a timeout",
      "Build a login form: code structure, state, validation, accessibility, security",
      "Behavioral: deep dive into past projects, SDLC, debugging production issues, observability, knowing when not to optimize",
    ],
  },
  {
    sourceFile: "33.txt",
    prompts: [
      "Build a reusable UI component with focus on modularity, performance, and design tradeoffs",
      "Service Workers — what they do and how to use them",
      "What is CORS and how does it work?",
      "Critical Rendering Path (CRP) — how the browser renders a page",
      "REST APIs — design and conventions",
      "HTTP caching strategies",
      "JavaScript script loading strategies (defer, async, modulepreload)",
      "Behavioral: motivation and reasons for joining the company",
    ],
  },
  {
    sourceFile: "34.txt",
    prompts: [
      "Implement a flatten array function",
      "Build a custom timer hook in React",
      "Build a Google Calendar–style view",
      "Implement a debounce function",
      "Build an accordion component",
      "Implement an event emitter",
      "Implement a DOM-like data structure",
      "Build a Capital–Country game",
      "Build a File Explorer component",
      "Build an OTP component",
      "Build a Grid Toggle component",
      "Build a Priority-Based Modals system",
      "Implement a Chainable Driver class",
      "Build a Cursor Tracker",
      "Build a Dynamic Grid challenge",
      "Build a Transaction Confirmation flow",
    ],
  },
  {
    sourceFile: "35.txt",
    prompts: [
      "Compare two linked lists",
      "Longest substring without repeating characters (sliding window)",
      "Sliding window maximum (deque-based optimization)",
      "Designing browser-like features",
      "Performance, SSR, and SEO — what matters and how they interact",
    ],
  },
  {
    sourceFile: "36.txt",
    prompts: [
      "Build a fully functional React application from scratch (state management, forms, component architecture)",
      "Build an Image Carousel component",
    ],
  },
  {
    sourceFile: "42.txt",
    prompts: [
      "Traverse a deeply nested object and resolve values of all functions inside it",
    ],
  },
  {
    sourceFile: "44.txt",
    prompts: [
      "Interface vs Type in TypeScript — when to use each",
      "Why Tailwind CSS over Bootstrap or traditional CSS?",
      "Have you used Jest / React Testing Library? How do you test components and API flows?",
      "How would you cancel an in-flight API request? (AbortController, Axios cancel token)",
      "How do you detect a memory leak in a React or frontend application?",
      "What is a hydration error in Next.js and why does it happen?",
      "If you store data in localStorage on one domain, can another domain access it?",
      "Why is code splitting better than loading everything at once?",
      "What are dynamic imports and what do they enable?",
      "Difference between code splitting and chunking",
      "What is git rebase and how does it differ from merge?",
      "How do you keep an eye on production bundle size?",
    ],
  },
  {
    sourceFile: "47.txt",
    prompts: [
      "How would you build and publish your own npm package?",
      "Library API design decisions to consider",
      "ESM vs CJS output for a published library",
      "Peer dependencies — when and how to use them",
      "Tree-shakable library design",
      "Type definitions for a JS library — strategies",
      "Backward compatibility for a published package",
      "Release strategy for a JS library (semver, changesets)",
    ],
  },
  {
    sourceFile: "48.txt",
    prompts: [
      "Explain the event loop and how asynchronous tasks are executed in JavaScript",
      "Implement a custom hook that debounces an input value",
      "Create a reusable dropdown component with search and multi-select",
      "How would you optimize React rendering for large lists (10k+ rows)?",
      "Difference between controlled and uncontrolled components in React",
      "Design a scalable React application for a dashboard with 100+ pages",
      "How code splitting and lazy loading improve performance",
      "How do you handle API rate limits gracefully on the frontend?",
      "What is hydration in Next.js and when can it cause UI mismatches?",
      "How would you build a component library used by multiple teams?",
      "CSR vs SSR vs SSG — when would you use each?",
      "How would you design a frontend architecture that handles 1M+ users daily?",
      "Behavioral: a critical production bug broke the UI — how did you handle it?",
      "Behavioral: how do you prioritize technical debt vs new features?",
      "Behavioral: how do you handle conflicts with designers or backend teams?",
      "Behavioral: how do you communicate complex technical decisions to non-technical stakeholders?",
    ],
  },
  {
    sourceFile: "49.txt",
    prompts: [
      "Explain JavaScript execution context, async behavior, and the event loop",
      "Find top-k elements in an array",
      "Difference between arrow functions and normal functions",
      "Build a React list with collapse/expand feature",
      "Build a reusable Button component with variants and sizes (like MUI)",
      "Reflow vs repaint in the browser — when each happens",
      "Why is `transform` preferred over animating layout properties?",
      "Event propagation in JavaScript: bubbling vs capturing",
      "Write a Promise polyfill with real-world use cases",
      "Implement an async scheduler with max concurrency",
      "Big list rendering: windowing and virtualization",
      "Build React-like class components from scratch in ES5",
      "Frontend system design: a Pinterest-like grid UI",
      "HLD walkthrough of your current/past frontend system",
    ],
  },
  {
    sourceFile: "52.txt",
    prompts: [
      "Tell me about a React performance optimization you implemented that failed",
      "How do you measure and quantify the impact of a performance fix?",
      "How do you distinguish React-side vs browser-rendering bottlenecks?",
    ],
  },
  {
    sourceFile: "54.txt",
    prompts: [
      "Explain the JavaScript event loop and how it works",
      "Explain the Critical Rendering Path and the CSSOM",
      "Write a polyfill for Function.prototype.bind",
      "How do you make a web app responsive (media queries, relative units)?",
      "What does forwardRef do, and when would you reach for useImperativeHandle?",
      "What is prop drilling and how do you avoid it?",
      "Explain Client-Side Rendering and when it's beneficial",
      "How would you design the data model for a chat application UI in React?",
      "Which CSS properties should you avoid animating, and why prefer transform/opacity?",
      "What are resource hints (preload, prefetch, dns-prefetch, preconnect)?",
      "How would you improve Interaction to Next Paint (INP)?",
      "Design the Send Message feature like Slack (UI + client logic)",
      "How would you build maps.google.com (tile loading, performance, UI responsiveness)?",
    ],
  },
  {
    sourceFile: "55.txt",
    prompts: [
      "Build a tile-based File Explorer in React (tree data, traversal, breadcrumbs, arbitrary nesting)",
    ],
  },
  {
    sourceFile: "56.txt",
    prompts: [
      "Design the frontend for a product listing page (component structure, state, data flow, edge cases, scalability)",
    ],
  },
  {
    sourceFile: "57.txt",
    prompts: [
      "How do you use React's useOptimistic for instant UI updates?",
      "How do you cancel API requests with AbortController?",
      "Synthetic Events in React — how do they differ from native DOM events?",
      "Why are noopener and noreferrer important on `<a target=\"_blank\">`?",
      "How does useActionState manage async actions and form state?",
      "How does tree shaking remove unused code in bundlers?",
      "Why does the viewport meta tag matter for mobile UI?",
      "When should you use refs instead of state in React?",
    ],
  },
  {
    sourceFile: "60.txt",
    prompts: [
      "Implement a Fetcher class with get(id) and post(id, x) methods that throw on missing/duplicate ids",
    ],
  },
  {
    sourceFile: "61.txt",
    prompts: [
      "How would you optimize a React application rendering 100k+ items in a list?",
      "What strategies improve page load time for a global audience?",
      "How do you identify and fix a memory leak in a production SPA?",
      "How do you manage dependencies when a library upgrade breaks a component?",
      "How would you debug a performance bottleneck in React using DevTools?",
      "How would you migrate a legacy frontend codebase to a modern framework?",
      "How do you ensure secure handling of sensitive user data on the client side?",
      "How do you troubleshoot intermittent UI glitches across browsers?",
      "A critical UI feature is failing during peak traffic — how do you mitigate?",
      "How do you manage state in a complex app to avoid unnecessary re-renders?",
      "How would you implement a robust frontend monitoring and logging system?",
      "How do you render a large dataset without blocking the main thread?",
      "How would you implement A/B testing without affecting current users?",
      "A CSS animation is janky on mobile — how do you identify and fix it?",
      "How do you handle real-time updates in a React application efficiently?",
    ],
  },
  {
    sourceFile: "65.txt",
    prompts: [
      "Why do functional updates (setCount(prev => prev + 1)) matter inside useCallback with empty deps?",
      "Why does setCount(count + 1) inside useCallback([], …) capture stale state?",
    ],
  },
  {
    sourceFile: "66.txt",
    prompts: [
      "Microtasks vs macrotasks — execution order in the event loop",
      "Closures and lexical scoping",
      "Hoisting and the Temporal Dead Zone",
      "How `this` differs between arrow and regular functions",
      "Object reference vs primitive comparison in JavaScript",
      "Prototypal inheritance in JavaScript",
      "Shallow vs deep copy",
      "Implicit vs explicit type coercion",
      "Truthy and falsy values and equality quirks",
      "Difference between == and ===",
      "Event delegation and bubbling",
      "typeof, instanceof, and reliable type checking",
      "Spread vs rest operators in JavaScript",
      "When NOT to use map / filter / reduce",
      "Currying and partial application",
      "async/await vs Promises vs callbacks",
      "Error handling in async JavaScript",
      "Critical rendering path — what blocks it?",
      "Repaint vs reflow and avoiding layout thrashing",
      "DNS resolution, TCP, TLS — the request lifecycle",
      "How browsers render HTML, CSS, and JS",
      "Preload, prefetch, and lazy loading",
      "Service workers and caching strategies",
      "CORS, preflight requests, and SameSite cookies",
      "Web storage APIs: localStorage, sessionStorage, cookies",
      "Accessibility best practices — ARIA, focus management, semantic HTML",
      "Responsive design principles (mobile-first, media queries, viewport units)",
    ],
  },
  {
    sourceFile: "67.txt",
    prompts: [
      "How does React's rendering process work under the hood?",
      "What causes unnecessary re-renders in React, and how do you prevent them?",
      "When should you NOT use useEffect?",
      "How does React.memo differ from useMemo and useCallback?",
      "What are the real-world use cases of React Suspense?",
      "How does lazy loading improve performance?",
      "What is state colocation and why does it matter?",
      "How do you structure a scalable React application?",
      "What are common performance bottlenecks in React apps?",
      "How does React handle event delegation?",
      "How do you debug performance issues in React?",
      "What are common mistakes developers make in production React apps?",
      "How do you manage global state efficiently in React?",
    ],
  },
  {
    sourceFile: "69.txt",
    prompts: [
      "Behavioral: how do you handle vague requirements?",
      "Behavioral: communication between different teams",
      "Behavioral: AI usage in your workflow",
      "DSA: graph-based optimization problem",
      "Build a Phone Screen–style web app (LLD)",
      "Frontend system design: build a Facebook social media feed",
    ],
  },
  {
    sourceFile: "73.txt",
    prompts: [
      "Largest Contentful Paint (LCP) — what slows it down and how to fix it",
      "Interaction to Next Paint (INP) — replacing FID, how to improve it",
      "Cumulative Layout Shift (CLS) — visual stability and how to control it",
      "First Contentful Paint (FCP) — what blocks it",
      "Time to First Byte (TTFB) — measuring and improving server response",
      "Total Blocking Time (TBT) — main-thread blocking and how to reduce it",
    ],
  },
  {
    sourceFile: "75.txt",
    prompts: [
      "Implement limitConcurrency(tasks, limit) using a worker-pool pattern",
    ],
  },
  {
    sourceFile: "77.txt",
    prompts: [
      "Rendering techniques: CSR vs SSR vs Streaming",
      "Build an Accordion with animation and styling",
      "How do you measure performance in real-world projects?",
      "Coding: execute a list of promises in series (no parallelism)",
      "Build a File Explorer UI",
      "Build a priority-based data fetching system",
    ],
  },
  {
    sourceFile: "84.txt",
    prompts: [
      "Implement a polyfill for Function.prototype.bind from scratch",
      "Implement currying in JavaScript",
      "Build an event emitter",
      "Build a cricket scoreboard UI (LLD)",
      "Build a custom timer / stopwatch component",
      "Build an autocomplete like Flipkart's Search Bar (HLD)",
    ],
  },
  {
    sourceFile: "85.txt",
    prompts: [
      "Flatten a nested array with custom ordering (top-level first, then nested)",
      "Output-based: what does `obj.print()` log when print uses `this.value`?",
      "How do you preserve object context when calling a detached method later?",
      "Implement a polyfill for Function.prototype.bind",
      "Implement a simplified pub/sub or selector/dispatch state subscription system",
      "Explain CSS position values: static, relative, absolute, fixed, sticky",
      "How to assign different widths to flex items?",
    ],
  },
  {
    sourceFile: "86.txt",
    prompts: [
      "Build an Accordion (most-tested UI behavior)",
      "Build a Modal (focus trap, ARIA, escape to close)",
      "Build a Tabs component (keyboard navigation, ARIA tabs pattern)",
      "Build an Image Carousel",
      "Build a Star Rating component",
      "Build a Progress Bar component",
      "Build a To-Do app with add/edit/delete and filters",
      "Build a Stopwatch / Timer",
      "Build a Shopping Cart UI",
      "Build a search input with debounce and live API",
      "Build an infinite-scroll list",
      "Build a File Explorer UI",
      "Build a drag-and-drop interaction",
      "Build a virtualized list for very large datasets",
      "Build a form builder",
      "Build a multi-step form with cross-step validation",
      "Implement dark mode and theming",
      "Frontend architecture: large-scale React app structure",
      "Frontend architecture: routing strategy",
      "Frontend architecture: state management layers",
      "Frontend system design: e-commerce frontend with filters and listing scale",
      "Frontend system design: a real-time dashboard",
      "Frontend system design: an offline-first app",
    ],
  },
  {
    sourceFile: "88.txt",
    prompts: [
      "Design and implement an ATM Machine (LLD: ATM, BankAccount, Card, Transaction, CashDispenser)",
    ],
  },
  {
    sourceFile: "89.txt",
    prompts: [
      "Populating Next Right Pointers in Each Node (binary tree)",
      "Intersection of Two Linked Lists",
      "LLD: design a Delivery System UI from a driver's perspective (real-time tracking, ETA, multi-order)",
    ],
  },
];

export function manualExtractedQuestions(): ExtractedQuestion[] {
  const out: ExtractedQuestion[] = [];
  for (const entry of MANUAL) {
    for (const title of entry.prompts) {
      out.push({
        rawTitle: title,
        rawHints: [],
        sourceFile: entry.sourceFile,
        context: "manual-prompt",
      });
    }
  }
  return out;
}
